# Generated by Django 4.0.4 on 2022-06-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='companies/')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('address_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=255, verbose_name='Phone')),
                ('working_hours', models.CharField(max_length=255, verbose_name='Ish vaqti')),
                ('working_hours_ru', models.CharField(max_length=255, null=True, verbose_name='Ish vaqti')),
                ('working_hours_en', models.CharField(max_length=255, null=True, verbose_name='Ish vaqti')),
                ('working_hours_uz', models.CharField(max_length=255, null=True, verbose_name='Ish vaqti')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Infos',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Rasm')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='projects', to='core.category')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ReceiveContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('email', models.EmailField(max_length=255)),
                ('company', models.CharField(max_length=255, verbose_name='Kompaniya nomi')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon Nomer')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Xabar')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(verbose_name='Tajriba')),
                ('clients', models.IntegerField(verbose_name='Mijozlar')),
                ('projects', models.IntegerField(verbose_name='Proyektlar')),
                ('team', models.IntegerField(verbose_name='Jamoa Soni')),
            ],
        ),
        migrations.CreateModel(
            name='SmmProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='smm_projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_projects/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ('id',),
            },
        ),
    ]
